name: Nix

on: 
  - pull_request
  - push

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31.4.1
    - run: |
        nix flake check -L